apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres16
  namespace: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: postgres16
  template:
    metadata:
      labels:
        app: postgres16
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
        diun.include_tags: "16.*-alpine3.18"
    spec:
      containers:
        - name: postgres
          image: postgres:16.1-alpine3.18
          imagePullPolicy: "Always"
          resources:
            limits:
              memory: 512Mi
              cpu: "110m"
            requests:
              memory: 126Mi
              cpu: "10m"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres16-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: pvc-postgres16