apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres16
spec:
  selector:
    app: postgres16
  type: ClusterIP
  ports:
   - port: 5432
     targetPort: 5432
