apiVersion: v1
kind: ConfigMap
metadata:
  name: trafik-config
  namespace: traefik
data:
  traefik: |
    api:
      insecure: true
      dashboard: true
    accessLog: {}
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
        http:
          tls: {}
    providers:
      kubernetesingress: {}
      kubernetesCRD: {}
    certificatesResolvers:
      file:
        acme:
          email: "liviubogdanioan@gmail.com"
          storage: "/certif/file.json"
          certificatesDuration: 2160
          preferredchain: "ISRG Root X1"
          keytype: "RSA4096"
          dnschallenge:
            provider: "gandiv5"
            resolvers: 
              - "1.1.1.1:53"
              - "8.8.8.8:53"
    metrics:
      influxDB2:
        address: "http://influx2.houseofus.eu/"
        token: "{!INFLUXDB-TRAEFIK-TOKEN!}"
        org: "house"
        bucket: "trafik"
        pushInterval: 30s
        addServicesLabels: true
