kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
        diun.include_tags: "latest"
    spec:
      serviceAccountName: traefik-account
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: [ "sh", "-c", "chmod -v 600 /certif/file.json" ]
          securityContext:
            runAsGroup: 977
            runAsUser: 988
          volumeMounts:
            - name: certif
              mountPath: /certif
      containers:
        - name: traefik
          image: traefik:v3.3.3
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "65Mi"
              cpu: "18m"
            limits:
              memory: "150Mi"
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
            - name: websecure
              containerPort: 443
          env:
            - name: GANDIV5_API_KEY
              value: '{!GANDI_APIKEY!}'
            - name: TZ
              value: "Europe/Madrid"
          volumeMounts:
            - mountPath: /etc/traefik/
              name: config
            - mountPath: /certif/
              name: certif
      restartPolicy: "Always"
      volumes:
        - name: certif
          persistentVolumeClaim:
            claimName: pvc-traefik-unifi
        - name: config
          configMap:
            name: trafik-config
            items:
              - key: traefik
                path: traefik.yaml