apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: traefik
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: traefik-web-service
#  namespace: traefik
#spec:
#  type: NodePort
#  ports:
#    - targetPort: web
#      port: 80
#  selector:
#    app: traefik
#---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: NodePort
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 443
      name: websecure
      targetPort: 443