kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nextcloud
  namespace: nexcloud
  labels:
    type: nfs
    app: nextcloud
spec:
  storageClassName: nfs-01
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pool1/nfskube/nextcloud
    server: truenas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
    type: nfs
spec:
  storageClassName: nfs-01
  volumeName: pv-nextcloud
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi