apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: tig
  labels:
    app: loki
data: 
  loki-config.yml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    
    common:
      path_prefix: /tmp/loki
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
    
    storage_config:
      tsdb_shipper:
        active_index_directory: /tmp/data/tsdb-index
        cache_location: /tmp/data/tsdb-cache
    
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      # max_transfer_retries: 0
      wal:
        dir: /data/loki/wal
    
    limits_config:
      # max_query_lookback: 672h # 28 days
      # retention_period: 672h   # 28 days
      split_queries_by_interval: 1h
      query_timeout: 5m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 12
      ingestion_burst_size_mb: 24
      per_stream_rate_limit: 12MB
    
    querier:
      max_concurrent: 25
      extra_query_delay: 30s
      engine:
        # timeout: 5m
        max_look_back_period: 2m
      query_ingesters_within: 3h
    
    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100
          # redis:
          #  endpoint: redis://svc-redis.nextcloud.svc.cluster.local:6379
          #  password: myredispass
    
    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    compactor:
      working_directory: /tmp/data/retention
      delete_request_store: filesystem
      retention_enabled: true
    analytics:
      reporting_enabled: false
