kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-loki
  namespace: tig
  labels:
    type: nfs
    app: loki
spec:
  storageClassName: nfs-01
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/pool1/nfskube/loki
    server: truenas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-loki
  namespace: tig
  labels:
    app: loki
    type: nfs
spec:
  storageClassName: nfs-01
  volumeName: pv-loki
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi