kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-loki-unifi
  namespace: tig
  labels:
    type: nfs
    app: loki
spec:
  storageClassName: unifi-nfs-kube
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/nfs/shared/kube_nfs/loki
    server: unifinas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-loki-unifi
  namespace: tig
  labels:
    app: loki
    type: nfs
spec:
  storageClassName: unifi-nfs-kube
  volumeName: pv-loki-unifi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi