apiVersion: v1
kind: Service
metadata:
  name: svc-loki
  namespace: tig
  labels:
    app: loki
spec:
  selector:
    app: loki
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 3100
      port: 3100