kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-jellyfin
  namespace: jellyfin
  labels:
    type: nfs
    app: jellyfin
spec:
  storageClassName: nfs-01
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pool1/nfskube/jellyfin
    server: truenas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
    type: nfs
spec:
  storageClassName: nfs-01
  volumeName: pv-jellyfin
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi