kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-psono-unifi
  namespace: psono
  labels:
    type: nfs
    app: psono
spec:
  storageClassName: unifi-nfs-kube
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/shared/kube_nfs/psono
    server: unifinas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-psono-unifi
  namespace: psono
  labels:
    app: psono
    type: nfs
spec:
  storageClassName: unifi-nfs-kube
  volumeName: pv-psono-unifi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi