kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-psono-unifi
  namespace: psono
  labels:
    type: nfs
    app: psono
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: psono
    volumeAttributes:
      server: unifinas.houseofus.eu
      share: /var/nfs/shared/kube_nfs/psono
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-psono-unifi
  namespace: psono
  labels:
    app: psono
    type: nfs
spec:
  storageClassName: nfs-csi
  volumeName: pv-psono-unifi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi