kind: Service
apiVersion: v1
metadata:
  name: svc-psono-client
  namespace: psono
  labels:
    app: psono-client
spec:
  selector:
    app: psono-client
  ports:
    - name: http
      protocol: TCP
      port: 10101
      targetPort: 80
  type: NodePort