kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: ha-nginx
  name: ha-nginx
  namespace: home-assist
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ha-nginx
  template:
    metadata:
      labels:
        app: ha-nginx
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ha-nginx
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: ha-nginx
          image: linuxserver/nginx:1.20.2
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 40Mi
              cpu: "0.01"
            requests:
              memory: 28Mi
              cpu: "0.001"
          env:
            - name: TZ
              value: Europe/Madrid
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
            - containerPort: 443
              protocol: TCP
              name: https
          volumeMounts:
            - mountPath: /config
              name: ha-nginx
      restartPolicy: Always
      volumes:
        - name: ha-nginx
          persistentVolumeClaim:
            claimName: pvc-ha-nginx
      