kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-ha-nginx
  namespace: home-assist
  labels:
    app: ha-nginx
    type: nfs
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pool1/nfskube/ha_nginx
    server: truenas.houseofus.eu
