kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ha-nginx
  namespace: home-assist
  labels:
    app: ha-nginx
    type: nfs
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi