kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: homeassist
  name: homeassist
  namespace: home-assist
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: homeassist
  template:
    metadata:
      labels:
        app: homeassist
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
        diun.include_tags: "2023.2.*;2023.3.*"
    spec:
      containers:
        - name: homeassist
          image: homeassistant/home-assistant:2023.2.3
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 1024Mi
              cpu: "0.50"
            requests:
              memory: 670Mi
              cpu: "0.20"
          env:
            - name: TZ
              value: Europe/Madrid
          ports:
            - containerPort: 8123
              protocol: TCP
              name: http
          volumeMounts:
            - name: ha-data
              mountPath: /config
      restartPolicy: Always
      volumes:
        - name: ha-data
          persistentVolumeClaim:
            claimName: pvc-homeassist