kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-homeassist-unifi
  namespace: home-assist
  labels:
    app: homeassist
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: homeassist
    volumeAttributes:
      server: unifinas.houseofus.eu
      share: /var/nfs/shared/kube_nfs/ha_config
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-homeassist-unifi
  namespace: home-assist
  labels:
    app: homeassist
spec:
  storageClassName: nfs-csi
  volumeName: pv-homeassist-unifi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi