kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-homeassist
  namespace: home-assist
  labels:
    app: homeassist
    type: nfs
spec:
  storageClassName: nfs-01
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pool1/nfskube/homeassist
    server: truenas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-homeassist
  namespace: home-assist
  labels:
    app: homeassist
    type: nfs
spec:
  storageClassName: nfs-01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi