kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-homeassist
  namespace: home-assist
  labels:
    app: homeassist
    type: nfs
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi