# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - kube-config/storage/smb_csi/values.yaml

pool:
  name: Default

steps:

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm repo add csi-driver-smb https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
      helm repo update
    failOnStderr: true
  displayName: 'Add and update Helm repository'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm upgrade \
        --install csi-driver-smb csi-driver-smb/csi-driver-smb \
        --create-namespace --namespace csi-driver-smb \
        -f $(System.DefaultWorkingDirectory)/kube-config/storage/smb_csi/values.yaml
    failOnStderr: true
  displayName: 'Upgrade csi driver smb'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl get pods -n csi-driver-smb
      kubectl wait --for=condition=Ready pods --all --namespace csi-driver-smb --timeout=180s
    failOnStderr: true
  displayName: 'Validate all pods are running'
