# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
 paths:
   include:
     - kube_apps/diun/*.yaml

pool:
  name: Default

variables:
  - name: telegram-token-houseofus
    value: $(telegram-token)

steps:
- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/kube_apps/diun/get_image_name.sh'
    failOnStderr: true

- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'my_dockerHub'
    repository: 'diun'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '-t $(img)'
    # '-t bogdanioanliviu/diun:$(Build.BuildId)' # $(img)
