# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
 paths:
   include:
     - kube_apps/diun/*

pool:
  name: Default

variables:
  - name: telegram-token-houseofus
    value: $(telegram-token)

steps:
- task: replacetokens@3
  displayName: 'Update manifests'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/kube_apps/diun/'
    targetFiles: '**/*.yaml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: true
    actionOnNoFiles: 'fail'
    enableTransforms: false
    tokenPrefix: '{'
    tokenSuffix: '}'
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/diun/deploy-diun.yaml'
    failOnStderr: true
    noProfile: false
