# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
   include:
     - kube_apps/gandi-dns/*

pool:
  name: Default

steps: 
- task: replacetokens@3
  displayName: 'Update manifests'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/kube_apps/gandi-dns/'
    targetFiles: '**/*.yaml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: true
    actionOnNoFiles: 'fail'
    enableTransforms: false
    tokenPrefix: '{'
    tokenSuffix: '}'
    enableRecursion: false
    useLegacyPattern: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/gandi-dns/deploy-gandi-dns.yaml
      if ! kubectl -n gandi-dns rollout status deployment gandi-dns; then
        kubectl -n gandi-dns rollout undo deployment gandi-dns
        kubectl -n gandi-dns rollout status deployment gandi-dns
        exit 1
      fi
    failOnStderr: true