# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - kube_apps/grafana_alloy/values.yaml
      - kube_apps/grafana_alloy/configmap_alloy.yaml

pool:
  name: Default

variables:
  - template: /kube_apps/pipelines/variables/varibles.yaml
steps:

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm repo add grafana https://grafana.github.io/helm-charts
      helm repo update
    failOnStderr: true
  displayName: 'Add and update Helm repository'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/grafana_alloy/configmap_alloy.yaml
    failOnStderr: true
    noProfile: false
  displayName: "Update config for alloy."

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm upgrade --install \
        --namespace grafana-alloy \
        --create-namespace \
        gfalloy grafana/alloy \
        -f $(System.DefaultWorkingDirectory)/kube_apps/grafana_alloy/values.yaml \
        --version $(grafana_alloy_helm_version)
    failOnStderr: true
  displayName: 'Upgrade Grafana alloy'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl get pods -n grafana-alloy
      kubectl wait --for=condition=Ready pods --all --namespace grafana-alloy --timeout=360s
    failOnStderr: true
  displayName: 'Validate all pods are running'
