# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 paths:
   include:
     - kube_apps/homeassistant/*

pool:
  name: Default

steps:

- task: replacetokens@3
  displayName: 'Update manifests'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/kube_apps/homeassistant/'
    targetFiles: '**/*.yaml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: true
    actionOnNoFiles: 'fail'
    enableTransforms: false
    tokenPrefix: '{'
    tokenSuffix: '}'
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/homeassistant/deploy-homeassist.yaml
      kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/homeassistant/svc-ha-coIoT.yaml
      kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/homeassistant/svc-homeassist-cluster.yaml
      kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/homeassistant/ingress-ha.yaml
    failOnStderr: true
    noProfile: false
  displayName: "Deploy new ha img."
