# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - kube_apps/tig/deploy-influx.yaml
      - kube_apps/tig/influxdb-secrets.yaml
      - kube_apps/tig/influxdb-config.yaml
      - kube_apps/tig/svc-influx.yaml
      - kube_apps/tig/ingress-influx.yaml
      - kube_apps/tig/svc-influx-cluster.yaml

pool:
  name: Default

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f ./kube_apps/tig/pv-pvc.yaml
      kubectl apply -f ./kube_apps/tig/influxdb-config.yaml
      kubectl apply -f ./kube_apps/tig/influxdb-secrets.yaml
      kubectl apply -f ./kube_apps/tig/svc-influx-cluster.yaml
      kubectl apply -f ./kube_apps/tig/ingress-influx.yaml
      kubectl apply -f ./kube_apps/tig/deploy-influx.yaml
    failOnStderr: true
