# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 paths:
   include:
     - kube_apps/tig/deploy-influx.yaml
     - kube_apps/tig/influxdb-secrets.yaml

pool:
  name: Default

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: | 
      kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/tig/deploy-influx.yaml 
      -f $(System.DefaultWorkingDirectory)/kube_apps/tig/influxdb-secrets.yaml
    failOnStderr: true
