# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - kube_apps/grafana_loki/configMap_promtail.yaml
      - kube_apps/grafana_loki/deploy-promtail.yaml
      - kube_apps/grafana_loki/serviceaccount_promtail.yaml
      - kube_apps/grafana_loki/svc-promtail.yaml

pool:
  name: Default

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f ./kube_apps/grafana_loki/configMap_promtail.yaml
      kubectl apply -f ./kube_apps/grafana_loki/deploy-promtail.yaml
      kubectl apply -f ./kube_apps/grafana_loki/serviceaccount_promtail.yaml
      kubectl apply -f ./kube_apps/grafana_loki/svc-promtail.yaml
    failOnStderr: true
    noProfile: false
