# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 paths:
   include:
     - kube_apps/psono/deploy-psono.yaml

pool:
  name: Default

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/psono/deploy-psono.yaml
    failOnStderr: true
    noProfile: false
  displayName: "Deploy new img."

