# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 paths:
   include:
     - kube_apps/psono/cron-psono.yaml

pool:
  name: Default

steps:  

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'kubectl apply -f ./kube_apps/psono/deploy-psono-client.yaml'
    failOnStderr: true
    noProfile: false
  displayName: 'Update psono cronjob.'
