trigger:
  paths:
    include:
      - kube_apps/semaphore-ui/semaphore-ingress.yaml
      - kube_apps/semaphore-ui/svc-semaphore.yaml
      - kube_apps/semaphore-ui/variables.yaml


pool:
  name: Default

variables:
  - template: /kube_apps/semaphore-ui/variables.yaml

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        wget https://github.com/semaphoreui/semaphore/releases/download/v$(semaphore_ui_version)/semaphore_$(semaphore_ui_version)_linux_amd64.deb
        sudo dpkg -i semaphore_$(semaphore_ui_version)_linux_amd64.deb
        rm semaphore_$(semaphore_ui_version)_linux_amd64.deb
        sudo systemctl daemon-reload
        sudo systemctl restart semaphore.service
      failOnStderr: true
    displayName: 'Install Semaphore UI version $(semaphore_ui_version)'