trigger:
  paths:
    include:
      - Ansible_docker/semaphore-ui.yaml


pool:
  name: Default

variables:
  - template: /Ansible_docker/semaphore-ui.yaml

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      SEMAPHORE_DEB="/tmp/semaphore_$(semaphore_version)_linux_amd64.deb"
      wget -q https://github.com/semaphoreui/semaphore/releases/download/v$(semaphore_version)/semaphore_$(semaphore_version)_linux_amd64.deb -O $SEMAPHORE_DEB
      echo "Running dpkg install with sudo..."
      sudo -n dpkg -i $SEMAPHORE_DEB
      echo "Reloading systemd daemon..."
      sudo -n systemctl daemon-reload
      echo "Restarting semaphore service..."
      sudo -n systemctl restart semaphore.service
      rm -f $SEMAPHORE_DEB
    failOnStderr: true
  displayName: 'Update Semaphore UI'

