trigger:
  paths:
    include:
      - kube_apps/traeffik/values.yaml

pool:
  name: Default

steps:
- task: replacetokens@5
  displayName: 'Update manifests'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/kube_apps/traeffik/'
    targetFiles: '**/*.yaml'
    encoding: 'auto'
    tokenPattern: 'custom'
    tokenPrefix: '{!'
    tokenSuffix: '!}'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: true
    actionOnNoFiles: 'fail'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm repo add traefik https://traefik.github.io/charts
      helm repo update
    failOnStderr: true
  displayName: 'Add and update Helm repository'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm upgrade --install traefik traefik/traefik \
        --namespace traefik1 \
        --create-namespace \
        -f $(System.DefaultWorkingDirectory)/kube_apps/traeffik/values.yaml \
        --version 37.1.0
    failOnStderr: true
  displayName: 'Upgrade Traefik'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl get pods -n traefik1
      kubectl wait --for=condition=Ready pods --all --namespace traefik1 --timeout=180s
    failOnStderr: true
  displayName: 'Validate all pods are running'
