# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 paths:
   include:
     - kube_apps/trivy-operator/*

pool:
  name: Default

steps:  

- task: replacetokens@3
  displayName: 'Update manifests'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/kube_apps/trivy-operator/'
    targetFiles: '**/*.yaml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: true
    actionOnNoFiles: 'fail'
    enableTransforms: false
    tokenPrefix: '{!'
    tokenSuffix: '!}'
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: "kubectl delete -f $(System.DefaultWorkingDirectory)/kube_apps/trivy-operator/deploy-trivy-operator.yaml"
#    failOnStderr: true
#    noProfile: false
#  displayName: "Remove old version of trivy."

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/trivy-operator/deploy-trivy-operator.yaml
    failOnStderr: true
    noProfile: false
  displayName: "Deploy new trivy img."
