kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          image: quay.io/yonatankahana/nfs-subdir-external-provisioner:pr207
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: truenas/nfs
            - name: NFS_SERVER
              value: truenas.houseofus.eu
            - name: NFS_PATH
              value: /mnt/pool1/nfskube
      volumes:
        - name: nfs-client-root
          nfs:
            server: truenas.houseofus.eu
            path: /mnt/pool1/nfskube
