apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
        diun.include_tags: "12.*"
    spec:
      containers:
        - name: postgres
          image: postgres:12.12-alpine3.16
          imagePullPolicy: "Always"
          resources:
            limits:
              memory: 600Mi
              cpu: "0.20"
            requests:
              memory: 126Mi
              cpu: "0.01"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      priorityClassName: db-priority
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: pvc-postgres