kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-postgres15
  namespace: postgres
  labels:
    app: postgres15
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pool1/nfskube/postgres15
    server: truenas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgres15
  namespace: postgres
  labels:
    app: postgres15
spec:
  storageClassName: managed-nfs-storage
  volumeName: pv-postgres15
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi