kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-postgres15-unifi
  namespace: postgres
  labels:
    app: postgres15
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: postgres15
    volumeAttributes:
      server: unifinas.houseofus.eu
      share: /var/nfs/shared/kube_nfs/postgres15
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgres15-unifi
  namespace: postgres
  labels:
    app: postgres15
spec:
  storageClassName: nfs-csi
  volumeName: pv-postgres15-unifi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi