apiVersion: v1
kind: Service
metadata:
  name: postgres15
  namespace: postgres
  labels:
    app: postgres15
spec:
  selector:
    app: postgres15
  type: ClusterIP
  ports:
   - port: 5432
     targetPort: 5432
