kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: gandi-dns
  namespace: gandi-dns
  name: gandi-dns
spec:
  replicas: 1
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: gandi-dns
  template:
    metadata:
      labels:
        app: gandi-dns
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
    spec:
      containers:
        - name: gandi-dns
          image: bogdanioanliviu/gandi:1172
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "15Mi"
              cpu: "10m"
            limits:
                memory: "29Mi"
          env:
            - name: TZ
              value: "Europe/Madrid"
            - name: APIKEY
              value: '{GANDI_APIKEY}'
            - name: RECORD_LIST
              value: 'psono;ha'
            - name: DOMAIN
              value: 'houseofus.eu'
      restartPolicy: Always