apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: tig
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf:1.21.4
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 120Mi
              cpu: "0.20"
            requests:
              memory: 40Mi
              cpu: "0.10"
          name: telegraf
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
              readOnly: true
          env:
            - name: INFLUX_TOKEN
              value: "0KAPkbAbxadTrvbk1kW3MVvtMAAdyUUCEnQX-yZ5Q0MOlaspCBdB0juSE8iQV8wQ5UxHff615EOOXT2x-MAYvw=="
      restartPolicy: Always
      volumes:
        - name: telegraf-config
          persistentVolumeClaim:
            claimName: pvc-telegraf
