apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: tig
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
        diun.include_tags: "latest;1.25.*"
    spec:
      containers:
        - image: telegraf:1.25.1
          imagePullPolicy: "Always"
          resources:
            limits:
              memory: 120Mi
              cpu: "0.20"
            requests:
              memory: 40Mi
              cpu: "0.10"
          name: telegraf
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
              readOnly: true
          env:
            - name: TZ
              value: "Europe/Madrid"
            - name: INFLUX_TOKEN
              value: "{telegraf_for influxdb}"
      restartPolicy: Always
      volumes:
        - name: telegraf-config
          persistentVolumeClaim:
            claimName: pvc-telegraf
            