apiVersion: v1
kind: ConfigMap
metadata:
  name: influx-secrets
  namespace: tig
  labels:
    app: influx
data:
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_USERNAME: influx_admin
  DOCKER_INFLUXDB_INIT_PASSWORD: change_value
  DOCKER_INFLUXDB_INIT_ORG: house
  DOCKER_INFLUXDB_INIT_BUCKET: galeata
  DOCKER_INFLUXDB_INIT_RETENTION: 1w
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: change_value
  INFLUXD_HTTP_IDLE_TIMEOUT: '0'
  TZ: "Europe/Madrid"