kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-grafana
  namespace: tig
  labels:
    type: nfs
    app: grafana
spec:
  storageClassName: nfs-01
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pool1/nfskube/grafana
    server: truenas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-grafana
  namespace: tig
  labels:
    app: grafana
    type: nfs
spec:
  storageClassName: nfs-01
  volumeName: pv-grafana
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi