kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-telegraf-unifi
  namespace: tig
  labels:
    type: nfs
    app: telegraf
spec:
  storageClassName: unifi-nfs-kube
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/shared/kube_nfs/telegraf
    server: unifinas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-telegraf-unifi
  namespace: tig
  labels:
    app: telegraf
    type: nfs
spec:
  storageClassName: unifi-nfs-kube
  volumeName: pv-telegraf-unifi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi