kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-influx-unifi
  namespace: tig
  labels:
    type: nfs
    app: influx
spec:
  storageClassName: unifi-nfs-kube
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/shared/kube_nfs/influx
    server: unifinas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-influx-unifi
  namespace: tig
  labels:
    app: influx
    type: nfs
spec:
  storageClassName: unifi-nfs-kube
  volumeName: pv-influx-unifi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi