kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: onlyoffice
  name: onlyoffice
  namespace: onlyoffice
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: onlyoffice
  template:
    metadata:
      labels:
        app: onlyoffice
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
    spec:
      containers:
        - name: onlyoffice
          image: onlyoffice/documentserver:7.2.1.34
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 1024Mi
              cpu: "0.80"
            requests:
              memory: 1024Mi
              cpu: "0.01"
          env:
            - name: JWT_ENABLED
              value: "true"
            - name: JWT_SECRET
              value: '{JWT-SECRET-onlyoffice}'
            - name: DB_HOST
              value: 'postgres15.postgres.svc.cluster.local'
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "onlyoffice"
            - name: DB_USER
              value: '{DB-USER-onlyoffice}'
            - name: DB_PWD
              value: '{DB-PWD-onlyoffice}'
            - name: SSL_CERTIFICATE_PATH
              value: '/var/www/onlyoffice/Data/certs/doc-onlyoffice.cer'
            - name: SSL_KEY_PATH
              value: '/var/www/onlyoffice/Data/certs/doc-onlyoffice.key'
          ports:
            - containerPort: 443
              protocol: TCP
              name: https
          volumeMounts:
            - mountPath: /var/www/onlyoffice/Data
              name: onlyoffice-data
              subPath: data
            - mountPath: /var/log/onlyoffice
              name: onlyoffice-data
              subPath: logs
            - mountPath: /var/lib/onlyoffice
              name: onlyoffice-data
              subPath: logs
            #- mountPath: /etc/onlyoffice/documentserver/nginx
            #  name: onlyoffice-data
            #  subPath: nginx
      restartPolicy: Always
      volumes:
        - name: onlyoffice-data
          persistentVolumeClaim:
            claimName: pvc-onlyoffice







