apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: onlyoffice
spec:
  limits:
  - default:
      cpu: 0.30
      memory: 1524Mi
    defaultRequest:
      cpu: 0.30
      memory: 1024Mi
    type: Container