kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-onlyoffice
  namespace: onlyoffice
  labels:
    type: nfs
    app: onlyoffice
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pool1/nfskube/onlyoffice
    server: truenas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-onlyoffice
  namespace: onlyoffice
  labels:
    app: onlyoffice
    type: nfs
spec:
  storageClassName: managed-nfs-storage
  volumeName: pv-onlyoffice
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi