apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: diun
  name: diun
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
    spec:
      serviceAccountName: diun
      securityContext:
        runAsUser: 977
        runAsGroup: 988
        #fsGroup: 0
        supplementalGroups: [ 0 ]
      containers:
        - name: diun
          image: crazymax/diun:4.31.0
          securityContext:
            runAsUser: 977
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "40Mi"
              cpu: "114m"
          env:
            - name: TZ
              value: "Europe/Madrid"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_JSON
              value: "false"
            - name: DIUN_WATCH_COMPAREDIGEST
              value: "true"
            - name: DIUN_WATCH_WORKERS
              value: "10"
            - name: DIUN_WATCH_SCHEDULE
              value: "0 */6 * * *"
            - name: DIUN_NOTIF_TELEGRAM_TOKEN
              value: "{telegram-token}"
            - name: DIUN_NOTIF_TELEGRAM_CHATIDS
              value: "-320842825"
            - name: DIUN_PROVIDERS_KUBERNETES
              value: "true"
            - name: PROVIDERS_KUBERNETES_NAMESPACES
              value: default,gandi-dns,postgres,psono,home-assist,traefik
            - name: DIUN_REGOPTS_DOKER_NAME
              value: docker.io
            - name: DIUN_REGOPTS_DOKER_SELECTOR
              value: name
            - name: DIUN_REGOPTS_DOKER_USERNAME
              value: "{docker-user}"
            - name: DIUN_REGOPTS_DOKER_PASSWORD
              value: "{docker-pass}"
          volumeMounts:
            - mountPath: "/data"
              name: "data"
      restartPolicy: Always
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: pvc-diun-unifi
