kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-diun-unifi
  namespace: diun
  labels:
    app: diun
    type: nfs
spec:
  storageClassName: unifi-nfs-kube
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/nfs/shared/kube_nfs/diun
    server: unifinas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-diun-unifi
  namespace: diun
  labels:
    app: diun
    type: nfs
spec:
  storageClassName: unifi-nfs-kube
  volumeName: pv-diun-unifi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi