kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-diun
  namespace: diun
  labels:
    app: diun
    type: nfs
spec:
  storageClassName: managed-nfs-storage
  volumeName: pv-diun
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi