apiVersion: v1
kind: Secret
metadata:
  name: pgpass12
  namespace: postgres
  labels:
    app: postgres
data:
  pgpass: cG9zdGdyZXMtc3ZjLnBvc3RncmVzLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzI6aGE6cG9zdGdyZXM6ZHI0ZGVyNQ==