---
# Secret for PostgreSQL superuser password
# Generate a secure password and update the value
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-superuser
  namespace: postgresql-db
type: Opaque
data:
  username: "{! postgres_user }!"
  password: "{! postgres_pass }!"
