kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nodered
  namespace: nodered
  labels:
    type: nfs
    app: nodered
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pool1/nfskube/nodeRed
    server: truenas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nodered
  namespace: nodered
  labels:
    app: nodered
    type: nfs
spec:
  storageClassName: managed-nfs-storage
  volumeName: pv-nodered
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi