apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres11-config
  namespace: postgres11
  labels:
    app: postgres11
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: dr4der5