apiVersion: v1
kind: Secret
metadata:
  name: postgres11-secret
  namespace: postgres11
  labels:
    app: postgres11
data:
  POSTGRES_DB: cG9zdGdyZXNkYg==
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password