- hosts: kmaster01
  vars:
    telegram_token: "{{ tele_token }}"
  tasks:
    - name: Get pods name
      shell: kubectl --kubeconfig=/home/bil/.kube/config -n nextcloud get pods --no-headers -o custom-columns=":metadata.name"
      register: pod_list
    - name: printout
      debug:
        msg:
          - "{{ pod_list.stdout_lines[0] }}"
    - name: Install new version using pod {{ pod_list.stdout_lines[0] }}
      shell: kubectl --kubeconfig=/home/bil/.kube/config -n nextcloud exec -it {{ pod_list.stdout_lines[0] }} -- sudo -u abc php /config/www/nextcloud/updater/updater.phar --no-interaction
      register: result
    - name: Send message to telegram Group if new version done
      telegram:
        token: '{{ telegram_token }}'
        chat_id: '-320842825'
        msg: "Sa actualizat Nextcloud la noua version."
      when: result.stdout_lines | length > 0
    - name: Send message to telegram Group if error happened
      telegram:
        token: '{{ telegram_token }}'
        chat_id: '-320842825'
        msg: "Exista errori la actualizare de versiune de Nextcloud."
      when: result.rc == 1