---
- hosts: docker01
  tasks:
    - name: Stop container
      docker_container:
        name: emby
        state: stopped
    - name: Remove container
      docker_container:
        name: emby
        state: absent
    - name: Remove image
      shell: docker rmi emby/embyserver:latest
    - name: Recreate container with new image
      docker_container:
        name: emby
        image: emby/embyserver:latest
        pull: yes
        state: started
        volumes:
          - "/home/bil/projects/datos/emby:/config"
          - "/home/bil/projects/datos/seafile_data/media:/mnt/share1"
        ports:
          - "8097:8096"
          - "8921:8920"
        env:
            TZ="Europe/Madrid"
            UID="1000"
            GID="1000"
        memory: 1G
        restart_policy: unless-stopped