---
- hosts: ansible_serv
  vars:
    telegram_token: "{{ tele_token }}"
  tasks:
    - name: Get infos on container
      docker_container_info:
        name: emby
      register: result
    - name: Does container exist?
      debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"
    - name: Print the status of the container
      debug:
        msg: "The container status is {{ result.container['State']['Status'] }}"
      when: result.exists
    - name: Send message to telegram Group
      telegram:
        token: '{{ telegram_token }}'
        chat_id: '-320842825'
        msg: "So terminat verificarea daca exista emby. Rezultatu e {{ result.exists }}"