kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-kuma
  namespace: kuma
  labels:
    type: nfs
    app: kuma
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pool1/nfskube/kuma
    server: truenas.houseofus.eu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-kuma
  namespace: kuma
  labels:
    app: kuma
    type: nfs
spec:
  storageClassName: managed-nfs-storage
  volumeName: pv-kuma
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi